### ISSUE TITLE
index.d.ts type-error

### ISSUE THREAD

**Issue by gtpan77** [bee-queue/bee-queue#310]
```
node_modules/bee-queue/index.d.ts:13:40 - error TS2314: Generic type 'Job<T>' requires 1 type argument(s).

13   backoffStrategies: Map<string, (job: BeeQueue.Job) => number>;
                                          ~~~~~~~~~~~~

node_modules/bee-queue/index.d.ts:120:30 - error TS2304: Cannot find name 'this'.

120       strategy: keyof typeof this.backoffStrategies,
                                 ~~~~

Found 2 errors.
```

**Comment by darkadept** [comment]
I was literally looking at this same error in my code when you posted this issue. Yes, I'm getting the exact same problem.

**Comment by skeggse** [comment]
Caused by #134, cc @calebboyd
